name: daybook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  pie_chart: 

  fluttertoast: 
  path_provider:
  video_player: ^1.0.1
  file_picker: ^2.1.6
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  path:
  image_picker: ^0.6.7+22
  curved_navigation_bar: ^0.3.7
  group_button: ^1.0.3
  intl: ^0.16.1
  cached_network_image: ^2.5.1
  sqflite: ^1.3.0
  google_fonts: ^1.1.2

  # state management
  provider: ^4.3.2+2
  flutter_local_notifications: ^1.4.4+1
  
  # icon of google
  font_awesome_flutter: ^8.10.0
  material_design_icons_flutter: 
  
  share: ^0.6.5+2
  url_launcher: ^5.7.10
  table_calendar:
  month_picker_dialog:
  charts_flutter: ^0.10.0

  pdf:
  flutter_full_pdf_viewer: ^1.0.6
  pdf_viewer_plugin: ^1.0.0+2
  open_file: ^3.0.3
  geocoding: ^1.0.5
  geolocator: ^6.1.11
  location: ^3.2.1
  permission_handler: ^5.0.1+1
  animated_text_kit:
  camera: ^0.6.0
  firebase_ml_vision: ^0.9.10
  flutter_swiper: ^1.1.6
  textfield_tags: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/logo.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/
    - assets/fonts/
    # - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
